services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "projectTMDT123@@"
      POSTGRES_DB: tmdt
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tmdt"]
      interval: 5s
      timeout: 5s
      retries: 12

  backend:
    build: ./backend
    ports:
      - "8001:8000"
    env_file: ./backend/.env
    environment:
      # Trong container kết nối qua service name "db" (port nội bộ 5432)
      DATABASE_URL: postgresql+asyncpg://postgres:projectTMDT123%40%40@db:5432/tmdt
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8001
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: "Admin123!"
    ports:
      - "5051:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  pgadmin_data:
